.TH hugo-push 1 "2026 Jul 29"
.SH NAME
hugo-push
.SH SYNOPSIS
hugo-push
.SH DESCRIPTION          \" Section Header - required - don't modify
hugo-push is a simple script which builds a hugo website and pushes it to
webspace using lftp. An example configuration with explainations is found at
\fI/usr/share/nanolx/hugo-push.conf\fP.

.SH FILES
.TP 15
/usr/share/nanolx/hugo-push.conf
example hugo-push configuration file
.PP

.SH AUTHORS
.TP 10
Christopher Roy Bratusek
nano@jpbjerlin.de
.PP