.TH nanolx-refind 1 "2026 Aug 23"
.SH NAME
nanolx-refind
.SH SYNOPSIS
nanolx-refind [themes-show] [themes-set \fItheme\fP] [themes-get] [themes-unset]
[enable-keep-refind] [disable-keep-refind]
.SH DESCRIPTION          \" Section Header - required - don't modify
nanolx-refind is a simple script to manage rEFInd bootloader themes, supports
showing installed themes, setting theme, showing current theme in use or
reverting to default.

It's looking for a \fIrefind\fP folder somewhere below \fI/boot\fP and uses it
as base folder for further actions.

.SH OPTIONS
nanolx-refind knows the following options
.TP 4
.B themes-show
List installed rEFInd themes
.TP
.B themes-set \fItheme\fP
Set given theme as new default
.TP
.B themes-get
Show which theme is currently in use
.TP
.B themes-unset
Revert to default theme
.TP
.B enable-keep-refind
add DPkg::Post-Invoke-Success configuration which will run refind-mkdefault when
grub/refind/shim are updated and rEFInd is found in efibootmgr list, ensuring
rEFInd will no longer be replaced by grub
.TP
.B disable-keep-refind
remove DPkg::Post-Invoke-Sucess configuration mentioned before
.PP

.SH AUTHORS
.TP 10
Christopher Roy Bratusek
nano@jpbjerlin.de
.PP