.TH nanolx-orbit 1 "2026 May 21"
.SH NAME
nanolx-orbit
.SH SYNOPSIS
nanolx-orbit [list] [download \fIpackge[s]\fP] [install \fIpackage[s]\fP] [clear]
.SH DESCRIPTION          \" Section Header - required - don't modify
nanolx-orbit is a simple script that manages installation of 3rdparty packages,
including some non-free packages, it's also checking sha256sums.

Currently supported packages: discord, citrix, citrix-usb, zoom,
zoom-vdi-plugin, openrgb plugins: effects, hwsync, fansync.

.TP 4
.B discord
.TP
.B citrix (icaclient)
.TP
.B citrix-usb
.TP
.B zoom
.TP
.B zomm-vdi-plugin
.TP
.B openrgb plugins
openrgb-effects, openrgb-hwsync and openrgb-fansync
.PP

nanolx-orbit stores all downloaded files at \fI/var/cache/nanolx\fP.

.SH OPTIONS
nanolx-orbit knows the following options
.TP 4
.B list
list all known packages, with links for further informations
.TP
.B download \fIpackge[s]\fP
download given packages, or all if no argument was passed and verify SHA256
checksum
.TP
.B install \fIpackge[s]\fP
download given packages, or all if no argument was passed, verify SHA256
checksum and install them (using \fIgdebi\fP for in-place dependency solving)
.TP
.B clear
remove all downloaded files from \fI/var/cache/nanolx\fP
.PP

.SH FILES
.TP 15
/usr/share/nanolx/nanolx-orbit.conf
nanolx-orbit configuration file
.PP

.SH AUTHORS
.TP 10
Christopher Roy Bratusek
nano@jpbjerlin.de
.PP
