.TH nanolx-ctx 1 "2026 May 22"
.SH NAME
nanolx-ctx
.SH SYNOPSIS
nanolx-ctx [enable-telemetry] [disable-telemetry] [check] [load-webkit] [unload-webkit]
[system-certs] [citrix-certs] [disable-scdlog] [enable-scdlog] [enable-padummy]
[disable-padummy] [enable-teams] [disable-teams] [restrict-local] [allow-local]
[register-zoom]
.SH DESCRIPTION          \" Section Header - required - don't modify
nanolx-ctx disables (or enable [...]) citrix telemetry and allows to run the
system check script bundled with citrix in an accessible manner.

If Citrix Workspace fails to start, webkitgtk2-4.0 is likely missing, as it's no
longer shipped with Debian (or Ubuntu). Citrix bundles it's own version, so you
may choose to install that version using using nanolx-ctx, at your own risk.

Starting with Citrix 26.04.0 Citrix works with webkitgtk2-4.1, so that's no
longer required.

.SH OPTIONS
nanolx-ctx knows the following options
.TP 4
.B disable-telemetry
Disable some citrix telemetry
.TP
.B enable-telemetry
Enable some citrix telemetry (why?)
.TP
.B check
Run the citrix workspace check script to check the system for missing packages.
.TP
.B load-webkit
Install citrix' bundled webkit2gtk-4.0 into your system
Note: this is no longer required with Citrix 26.04.0 so the script does nothing
.TP
.B unload-webkit
Uninstall citrix' bundled webkit2gtk-4.0 from your system
.TP
.B system-certs
Use \fI/etc/ssl/certs\fP instead of bundled certificates for citrix
.TP
.B citrix-certs
Use citrix' bundled certificates
.TP
.B disable-scdlog
Disable citrix smartcard logging, which creates gigantic log files, sucking up
all your disk space in literally no time (also useful if you have a Yubikey)
.TP
.B enable-scdlog
Enable citrix smarcard logging
.TP
.B enable-padummy
Install a dummy \fIpulseaudio\fP script, so we can trick citrix into using \fIpipewire\fP
Note: if you actually have pulseaudio installed, this does nothing
Note: this is only required for older Citrix versions, starting with 26.04.0
the script does nothing
.TP
.B disable-padummy
Uninstall the dummy \fIpulseaudio\fP script
.TP
.B enable-teams
Enable optimizations for Microsoft Teams
.TP
.B disable-teams
Disable optimizations for Microsoft Teams
.TP
.B restrict-local
Restrict citrix remote access to local machine, e.g. storage access or access to
local machine printer queue, see https://return42.github.io/handsOn/citrix/index.html#konfiguration
.TP
.B allow-local
Revert citrix remote acess to local machine to default settings
.TP
.B register-zoom
If Citrix gets uninstalled and reinstalled, but not zoomvdi-universal-plugin,
does not get reinstalled at the same time, the module is no longer active. This
force runs it's postinstallation script
.PP

.SH AUTHORS
.TP 10
Christopher Roy Bratusek
nano@jpbjerlin.de
.PP
