.TH nanolx-apt 1 "2026 May 18"
.SH NAME
nanolx-apt
.SH SYNOPSIS
nanolx-apt [list] [add \fIrepo\fP] [remove \fIrepo\fP] [check] [enable-config]
[disable-config] [enable-pinning] [disable-pinning]
.SH DESCRIPTION          \" Section Header - required - don't modify
nanolx-apt manages additional repository configurations, including key handling,
aswell as matching pinning and minor apt configuration changes (the latter both optional).

Currently known repos are:
.TP 5
.B debian
rolls-out full suite stable, testing, unstable, experimental
.TP
.B nanolx
My personal apt repostitory, see https://nanolx.org/photonic/
.TP
.B liquorix
Liquorix is an enthusiast Linux kernel designed for uncompromised responsiveness,
see https://liquorix.net/
.TP
.B i2p
The I2P network is a fully encrypted peer-to-peer overlay network, see https://deb.i2p.net/
.TP
.B winehq
Wine Is Not an Emulator, official WineHQ builds, see  https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu
.TP
.B deb-multimedia
The one and only deb-multimedia repo, see https://deb-multimedia.org/
.PP

It also checks the downloaded repository key's SHA256sum.

.SH OPTIONS
nanolx-apt knows the following options
.TP 4
.B list
Shows the list of supported repositories
.TP
.B add \fIrepo\fP
Enable given repository (downloads signing key)
.TP
.B remove \fIrepo\fP
Disable given repository
.TP
.B check
Check which repositories are enabled
.TP
.B enable-config
Enable nanolx apt configuration
.TP
.B disable-config
Disable nanolx apt configuration
.TP
.B enable-pinning
Enable nanolx apt pinning
.TP
.B disable-pinning
Disable nanolx apt pinning
.PP

.SH FILES
.TP 15
/usr/share/nanolx/nanolx-apt.conf
nanolx-apt configuration file

.TP
/usr/share/nanolx/apt.d/99nanolx
additional settings for apt

.TP
/usr/share/nanolx/apt.d/pinning
nanolx apt pinning configuration
.SH AUTHORS
.TP 10
Christopher Roy Bratusek
nano@jpbjerlin.de
.PP