# --- BASIC SETTINGS ---
resolution 0
use_graphics_for linux
hideui hints
showtools firmware

# --- ICONS & BACKGROUND ---
icons_dir themes/rEFInd-digital-void/icons
banner themes/rEFInd-digital-void/background.red3.png
banner_scale fillscreen

# --- ICON SIZES ---
big_icon_size 192
small_icon_size 96

# --- SELECTION HIGHLIGHTS ---
selection_small themes/rEFInd-digital-void/selection_small.png
selection_big themes/rEFInd-digital-void/selection_big.png
