#####
#
# hugo-ppush configuration
#
#####

# path to local apt repository
HUGO_PATH=/var/www/hugo

# ftp server for ftp push
HUGO_FTP_SRV=ftp.myserver.org

# directory on ftp server
HUGO_FTP_DIR=httpdocs/apt

# username for ftp push
HUGO_FTP_USR=myuser

# password for ftp push needs to be stored as
# GPG encrypted file in ${HOME}/.hugo-push.pw
#
# to do so, given you already have a GPG key,
# issue the following command:
#
# gpg --encrypt -r "YOUR_GPG_IDENTITY" > ${HOME}/.hugo-push.pw
#
# enter or paste the password and press Ctrl-D to exit
# GPG will now store an encrypted version of your input
# in the file ${HOME}/.hugo-push.pw and repokit will auto
# decrypt it when required, this will make your system's
# askpass to popup in order to unlock the GPG key
