#!/bin/sh
set -e

case "${1}" in
    remove | abort-install | disappear | purge)
        if [ ! -d "/usr/share/plymouth/themes/debian-mac-style/" ]; then
            echo "Unsetting debian-mac-style as default Plymouth theme."
            update-alternatives --remove default.plymouth \
                /usr/share/plymouth/themes/debian-mac-style/debian-mac-style.plymouth

            if command -v update-initramfs >/dev/null 2>&1; then
                update-initramfs -u -k all
            fi
        fi

        REFIND_CONF="/boot/efi/EFI/refind/refind.conf"
        if [ -f "$REFIND_CONF" ]; then
            if [ ! -d "/boot/efi/EFI/refind/themes/rEFInd-digital-void/" ]; then
                echo "Unsetting rEFInd-digital-void as default rEFInd theme."

                sed -i '/include themes\/rEFInd-digital-void\/theme.conf/d' "$REFIND_CONF"
                sed -i '/# Added by nanolx-themes on first install/d' "$REFIND_CONF"
            fi
        fi
    ;;
esac

# DEBHELPER #
exit 0
