#!/bin/sh
set -e

case "${1}" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        if deb-systemd-helper --quiet was-enabled 'ctxcwalogd.service'; then
            deb-systemd-helper enable 'ctxcwalogd.service' >/dev/null || true
        else
            deb-systemd-helper update-state 'ctxcwalogd.service' >/dev/null || true
        fi

        if deb-systemd-helper --quiet was-enabled 'ctxusbd.service'; then
            deb-systemd-helper enable 'ctxusbd.service' >/dev/null || true
        else
            deb-systemd-helper update-state 'ctxusbd.service' >/dev/null || true
        fi

        if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
            systemctl --system daemon-reload >/dev/null || true
            deb-systemd-invoke start 'system-ctxcwalogd.slice' 'ctxusbd.timer' >/dev/null || true
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`${1}'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
