#!/bin/sh
set -e

case "$1" in
    purge)
        deb-systemd-helper purge 'ctxcwalogd.service' 'ctxusbd.service' >/dev/null || true
    ;;

    remove)
        if [ -d /run/systemd/system ] ; then
            systemctl --system daemon-reload >/dev/null || true
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
