#!/bin/sh
set -e


case "$1" in
    install|upgrade)
        if [ -d /boot/efi/EFI/refind/themes/rEFInd-digital-void.old ]; then
            rm -rf /boot/efi/EFI/refind/themes/rEFInd-digital-void.old
    fi
        if [ -d /boot/efi/EFI/refind/themes/rEFInd-digital-void/ ]; then
            mv /boot/efi/EFI/refind/themes/rEFInd-digital-void/ \
               /boot/efi/EFI/refind/themes/rEFInd-digital-void.old/
    fi
    ;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
