#!/bin/sh
set -e

case "$1" in
    purge|remove)
        rm -rf /boot/efi/EFI/refind/themes/rEFInd-digital-void.old
        if command -v update-icon-caches >/dev/null; then
            update-icon-caches /usr/share/icons/Tela-red /usr/share/icons/Tela-red-dark
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
