#!/bin/bash

version="1.1.0"
reldate="2016/05/25"

_help () {

	echo "gfxrename v${version} (${reldate})
© 2015 - 2016 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
	gfxrename <directory> <prefix>

example:
	gfxrename /home/test/Pictures/Holiday Holiday-Winter-2016
"

}

fill_zeros () {
	current_len=${#1}
	diff_string=""

	if [[ ${current_len} -ne ${count_len} ]]; then
		diff_len=$((${count_len}-${current_len}))
		while test ${diff_len} -ne 0; do
			diff_string="${diff_string}0"
			diff_len=$((${diff_len}-1))
		done
		echo ${diff_string}
	fi
}

rename_files () {
	mkdir "${directory}"/tmp

	count_max=$(($(find "${directory}" -maxdepth 1 -type f | wc -l)))
	count_len=${#count_max}
	count_now=1

	OLD_IFS="${IFS}"
	export IFS=$'\n'

	files=$(find "${directory}" -maxdepth 1 -type f)

	for image in ${files[@]}; do
		suffix=$(fill_zeros ${count_now})${count_now}.${image##*.}
		mv "${image}" "${directory}"/tmp/"${prefix}"-"${suffix}"
		count_now=$(($count_now+1))
	done

	mv "${directory}"/tmp/* "${directory}"/
	rmdir "${directory}"/tmp

	export IFS="${OLD_IFS}"
}


if [[ $# -ne 2 ]]; then
	_help
else
	directory="${1}"
	if [[ ! -d "${directory}" ]]; then
		echo "directory ${directory} does not exist!"
		exit 1
	fi

	prefix="${2}"
	rename_files
fi
