#!/bin/bash

case ${1} in
	"" | "-h" | "--help" )
		echo -e "Usage: mksbuild <arch> <tree>

Examples:
	mksbuild i386 unstable
	mksbuild armhf testing"
	;;

	* )
		user=$(whoami)
		sudo apt-get install sbuild schroot ubuntu-dev-tools debootstrap
		sudo adduser ${user} sbuild
		mk-sbuild --arch=${1} --debootstrap-mirror=ftp://ftp.debian.org/debian/ ${2}
	;;
esac
