#!/bin/bash

user=$(whoami)

sudo apt-get install sbuild schroot ubuntu-dev-tools debootstrap
sudo adduser ${user} sbuild

mk-sbuild --arch=${1} --debootstrap-mirror=ftp://ftp.debian.org/debian/ ${2}
