# configuration for /usr/sbin/nanolx-apt

key_base=/usr/share/nanolx/trusted.d
sources_d=/usr/share/nanolx/sources.d

key_nanolx=https://www.nanolx.org/apt/photonic2026.asc
key_nanolx_store=${key_base}/nanolx2026.asc

key_liquorix=https://liquorix.net/liquorix-keyring.gpg
key_liquorix_store=${key_base}/liquorix.asc

key_winehq=https://dl.winehq.org/wine-builds/winehq.key
key_winehq_store=${key_base}/winehq.asc

key_i2p=https://geti2p.net/_static/i2p-archive-keyring.gpg
key_i2p_store=${key_base}/i2p.asc

debmultimedia_url=https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2024.9.1_all.deb
debmultimedia_pkg=deb-multimedia-keyring_2024.9.1_all.deb

# repo
repo_list="
debian:         https://debian.org [full suite: stable->experimental]
nanolx:         https://nanolx.org/photonic/
liquorix:       https://liquorix.net/
i2p:            https://deb.i2p.net/
winehq:         https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu
debmultimedia:  https://deb-multimedia.org/"

all_repos="debian nanolx liquorix i2p winehq deb-multimedia"
