#!/bin/bash

version="0.1.1"
reldate="2026/07/23"

SYSDIR=/etc/systemd/system

if [ -f nanolx-backup ]; then
    SERVICE="nanolx-backup.service"
    TIMER="nanolx-backup.timer"
else
    CFGDIR=/usr/share/nanolx
    SERVICE="${CFGDIR}/nanolx-backup.service"
    TIMER="${CFGDIR}/nanolx-backup.timer"
fi

manage_timers () {
    action="${1}"
    delete="${2}"

    mapfile -t timers < <(systemctl list-unit-files --type=timer "nanolx-backup*" | \
        gawk '/nanolx-backup/{print $1}')
    if [ -n "${timers[@]}" ]; then
        PS3="Select Entry (enter number): "
        select choice in "${timers[@]}" "Cancel"; do
            if [ "${choice}" = "Cancel" ]; then
                break
            elif [ -n "${choice}" ]; then
                systemctl "${action}" --now "${choice}"
                if ${delete}; then
                    rm -v "${choice%.timer}.{timer,service}"
                    systemctl daemon-reload
                fi
                break
            else
                echo "Invalid choice"
            fi
        done
    else
        echo "No timers created by nanolx-backup"
    fi
}

backup_create () {
    # ensure trailing /
    srcdir="${1%/}/"
    destdir="${2%/}/"
    period="${3:-daily}"

    # if systemd doesn't recognize the value of period, fallback to daily aswell
    if ! systemd-analyze calendar "${period}" &>/dev/null; then
        echo "period \"${period}\" not supported by systemd, falling back to \"daily\"."
        period="daily"
    fi

    # cleanup srcdir so it's usable as file name for service
    # eg.: /home/testuser -> .home.testuser
    # use [:alnum:] for all alphanumeric chars, not just latin
    # and to be double safe enforce C.UTF-8 locale
    name=$(echo "${srcdir%/}" | LC_ALL=C.UTF-8 sed 's,/,.,g;s/[^[:alnum:]._-]//g')
    service="nanolx-backup${name}.service"
    timer="nanolx-backup${name}.timer"

    if [ ! -d "${srcdir}" ]; then
        echo "Source directory: ${srcdir} does not exist!"
        exit 1
    fi

    if [ ! -d "$(dirname ${destdir})" ]; then
        echo "Toplevel directory: $(dirname ${destdir}) for backup does not exist!"
        exit 1
    fi

    sed -e "s#@SOURCE@#${srcdir}#;s#@DEST@#${destdir}#" "${SERVICE}" > \
        "${SYSDIR}/${service}"

    sed -e "s#@SOURCE@#${srcdir}#;s#@PERIOD@#${period}#" "${TIMER}" > \
        "${SYSDIR}/${timer}"

    systemctl daemon-reload
    systemctl enable --now "${timer}"
}

case "${1}" in
    create )
        backup_create "${2}" "${3}" "${4}"
    ;;

    list )
        systemctl list-timers --all "nanolx-backup*"
        systemctl list-unit-files --type=timer "nanolx-backup*"
    ;;

    list-short )
        systemctl list-unit-files --type=timer "nanolx-backup*" | \
            gawk '/nanolx-backup/{print $1}'
    ;;

    status )
        TIMERS=$(systemctl list-unit-files --type=timer "nanolx-backup*" | \
            gawk '/nanolx-backup/{print $1}')
        if [ -n "${TIMERS[@]}" ]; then
            STRING="TIMER ACTIVE ENABLED"
            for timer in "${TIMERS[@]}"; do
                # remove nanolx-backup prefix and .timer suffix
                _timer="${timer%.timer}"
                _timer="${_timer#nanolx-backup}"
                _active="$(systemctl is-active "${timer}")"
                _enabled="$(systemctl is-enabled "${timer}")"
                STRING+="\n${_timer} ${_active} ${_enabled}"
            done
            echo -e "${STRING}" | column -t
        else
            echo "No timers created by nanolx-backup"
        fi
    ;;

    disable )
        manage_timers disable false
    ;;

    enable )
        manage_timers enable false
    ;;

    delete )
        manage_timers disable true
    ;;

    help | * )
        echo "nanolx-backup v${version} (${reldate})
© 2026 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage   nanolx-backup [option], where [option] is one of:

    create source destination period
        period is optional, any value known to systemd (fallback is 'daily')

        typically: hourly, daily, weekly, monthly, quarterly or yearly

        others: Mon,Wed,Fri       (backup on theese days)
                \"Mon..Fri 22:00\"  (backup monday to friday on 22:00 (10:00 PM))
                    since this period contains a space, quote it
                use 'systemd-analyze calendar [period]' to validate

    list
        list timers created by nanolx-backup

    list-short
        list timers created by nanolx-backup (names only)

    status
        show status of timers created by nanolx-backup

    enable
        choose from nanolx-backup timers and enable them

    disable
        choose from nanolx-backup timers and disable them

    delete
        choose from nanolx-backup timers, disable and delete them
"
    ;;
esac