# version configuration for
# /usr/sbin/nanolx-orbit

discord_ver=1.0.143
discord_url="https://stable.dl2.discordapp.net/apps/linux/${discord_ver}/discord-${discord_ver}.deb"
discord_sha=466443bbda724766c6dee376041a607fc5cbdda40efd9019c108a06b0b15f5ba

zoom_ver=7.0.5.3034
zoom_url="https://zoom.us/client/${zoom_ver}/zoom_amd64.deb"
zoom_sha=9d1478ce9e67615a04fb00496ef8be332e42a3c730d08b9cd4c8141ce4a76113

zoom_vdi_ver=7.0.10.26980
zoom_vdi_url="https://zoom.us/download/vdi/${zoom_vdi_ver}/zoomvdi-universal-plugin-ubuntu_${zoom_vdi_ver%.*}.deb"
zoom_vdi_sha=dd6ea6988043dc29ff8ce62f7e1888c5ac93c8010b8919c84859f96ce87d3116

citrix_url="https:$(curl -sL \
https://www.citrix.com/downloads/workspace-app/linux/workspace-app-for-linux-latest.html | \
grep "icaclient.*amd64.deb?__gda__" | \
sed -e 's,.*rel=",,;s," id.*,,')"
citrix_pkg="${citrix_url%\?*}"
citrix_pkg="${citrix_pkg##*/}"
citrix_sha=7ce8c3a32e1e9d698e7bca349ad582136040774a49e35f47e529430918f8b94a

citrix_usb_url="https:$(curl -sL \
https://www.citrix.com/downloads/workspace-app/linux/workspace-app-for-linux-latest.html | \
grep "ctxusb.*amd64.deb?__gda__" | \
sed -e 's,.*rel=",,;s," id.*,,')"
citrix_usb_pkg="${citrix_usb_url%\?*}"
citrix_usb_pkg="${citrix_usb_pkg##*/}"
citrix_usb_sha=b5faa627342a423cb7019bc295d9a9d7fd2785285e2ded3a7a68f1cd8dc397f7

citrix_epa_url="https:$(curl -sL \
https://www.citrix.com/downloads/citrix-endpoint-analysis/plug-ins/EPA-Clients-Linux.html | \
grep -m 1 "nsepa.*.deb?__gda__" | sed -e 's,.*rel=",,;s," id.*,,')"
citrix_epa_ver="26.2.3"
citrix_epa_pkg="citrix-nsepa_${citrix_epa_ver}.deb"
citrix_epa_sha=47663f97ca7b83da6c84eb9857d1bb63e56f89220f66da329c0c3b57c7f90254

openrgb_effects_url=https://codeberg.org/OpenRGB/OpenRGBEffectsPlugin/releases/download/release_candidate_1.0rc2/OpenRGBEffectsPlugin_1.0rc2_Bookworm_amd64_415dc20.deb
openrgb_effects_sha=33c0f123dbc0f05021a467e2da03a2979e0db2a816798b929060c7a6bb44a9d2

openrgb_hwsync_url=https://codeberg.org/OpenRGB/OpenRGBHardwareSyncPlugin/releases/download/release_candidate_1.0rc2/OpenRGBHardwareSyncPlugin_1.0rc2_Bookworm_amd64_4aed949.deb
openrgb_hwsync_sha=655469df9098d7e0d64d9b10498bd789b495290a2d00dce165cb31f4ee8237a8

openrgb_fansync_url=https://codeberg.org/OpenRGB/OpenRGBFanSyncPlugin/releases/download/release_candidate_1.0rc2/OpenRGBFanSyncPlugin_1.0rc2_Bookworm_amd64_a33e472.deb
openrgb_fansync_sha=3bc3f2cd172377924c41d1a753f1ef959f4a547b1beaea3b665dace9dee47df4

# package_list
package_list="
discord:         ${discord_url##*/}
zoom:            ${zoom_url##*/} (${zoom_ver})
zoom-vdi:        ${zoom_vdi_url##*/}
citrix:          ${citrix_pkg}
citrix-usb:      ${citrix_usb_pkg}
citrix-epa:      ${citrix_epa_pkg}
openrgb-effects: ${openrgb_effects_url##*/}
openrgb-hwsync:  ${openrgb_hwsync_url##*/}
openrgb-fansync: ${openrgb_fansync_url##*/}"
