#!/bin/bash

version="0.0.5"
reldate="2026/08/23"

if (( EUID != 0 )); then
    echo "nanolx-refind must be run as root"
    exit 1
fi

refind_base=$(find /boot -type d -name 'refind')
if [ ! -d "${refind_base}" ]; then
    echo "no folder 'refind' found anywhere in /boot"
    exit 1
fi

if [ -f 99-keep-refind ]; then
    refind_apt_conf=99-keep-refind
else
    refind_apt_conf=/usr/share/nanolx/99-keep-refind
fi

refindconf=/boot/efi/EFI/refind/refind.conf

case ${1} in
    list-themes )
        ls -1 -I "*.old" "${refind_base}/themes/"
    ;;

    set-theme )
        if [ -d "${refind_base}/themes/${2}" ]; then
            echo "setting default refind theme: ${2}"
            sed -e '/include.*themes/d' -i "${refind_base}/refind.conf"
            echo "include themes/${2}/theme.conf" >> "${refind_base}/refind.conf"
        else
            echo "skip: theme not found: ${2}"
            exit 1
        fi
    ;;

    get-theme )
        echo "currently active refind theme:"
        refind_theme="$(gawk -F'/' '/include.*themes/{print $2}' "${refind_base}/refind.conf")"
        [ -z "${refind_theme}" ] && echo "default (none)" || echo "${refind_theme}"
    ;;

    default-theme )
        echo "reverting to default refind theme"
        sed -e '/include.*themes/d' -i "${refind_base}/refind.conf"
    ;;

    enable-keep-refind )
        if [ -f /etc/apt/apt.conf.d/99-keep-refind ]; then
            echo "Refind protection configuration already enabled"
        else
            cp ${refind_apt_conf} /etc/apt/apt.conf.d/
            echo "installed /etc/apt/apt.conf.d/99-keep-refind"
        fi
    ;;

    disable-keep-refind )
        if [ -f /etc/apt/apt.conf.d/99-keep-refind ]; then
            rm /etc/apt/apt.conf.d/99-keep-refind
            echo "removed /etc/apt/apt.conf.d/99-keep-refind"
        else
            echo "Refind protection configuration not enabled"
        fi
    ;;

    liquorix-default )
        if grep -q "^default_selection \"liquorix\"" ${refindconf}; then
            echo "liquorix already set as prefered kernel"
        else
            echo "set latest liquorix kernel as default boot choice"
            echo "fold_linux_kernels false" >> ${refindconf}
            echo "default_selection \"liquorix\"" >> ${refindconf}
        fi
    ;;

    debian-default )
        if grep -q "^default_selection \"liquorix\"" ${refindconf}; then
            echo "set latest upstream kernel as default boot choice"
            sed "/^fold_linux_kernels false/d" -i ${refindconf}
            sed "/^default_selection \"liquorix\"/d" -i ${refindconf}
        else
            echo "upstream already set as prefered kernel"
        fi
    ;;

    * )
        echo -e "nanolx-refind v${version} (${reldate})
© 2026 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
    nanolx-refind list-themes           list installed themes
    nanolx-refind set-theme     [theme] set theme to use
    nanolx-refind get-theme             get active theme
    nanolx-refind default-theme         revert to default theme
    nanolx-refind enable-keep-refind    keep refind as default bootloader,
                                        when updating grub/refind/shim
    nanolx-refind disable-keep-refind   disable keeping refind as default bootloader
    nanolx-refind liquorix-default      set latest liquorix kernel as default boot choice
    nanolx-refind debian-default        set latest upstream kernel as default boot choice
"
    ;;
esac