#!/bin/bash

version="0.0.2"
reldate="2026/05/16"

case ${1} in
    enable )
        sed 's,^[#][ ]SKEL=.*,SKEL=/etc/skel_nano/,' -i /etc/default/useradd
        sed 's,^[#][ ]SHELL=.*,SHELL=/bin/bash,' -i /etc/default/useradd
    ;;

    disable )
        sed 's,^SKEL=.*,# SKEL=/etc/skel/,' -i /etc/default/useradd
        sed 's,^SHELL=.*,# SHELL=/bin/sh,' -i /etc/default/useradd
    ;;

    * )
        echo -e "nanolx-skel v${version} (${reldate})
© 2026 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
    nanolx-skel enable
    nanolx-skel disable
"
    ;;
esac
