# version configuration for
# /usr/sbin/nanolx-orbit

discord_ver=1.0.138
discord_url="https://stable.dl2.discordapp.net/apps/linux/${discord_ver}/discord-${discord_ver}.deb"
discord_sha=e51900d802548d4f7dfe9838e2b98a874ea9cb63f688251e8cfd50b41d307f25

zoom_ver=7.0.0.1666
zoom_url="https://zoom.us/client/${zoom_ver}/zoom_amd64.deb"
zoom_sha=cd6237b14c070f3de2d8a7b2419c5647be61a354204b971529ef458add1c502d

zoom_vdi_ver=6.6.14.26970
zoom_vdi_url="https://zoom.us/download/vdi/${zoom_vdi_ver}/zoomvdi-universal-plugin-ubuntu_${zoom_vdi_ver%.*}.deb"
zoom_vdi_sha=2dcdf345e39e2fe90cff7435e2d435e9ea955402f2fb6e2f6f17e7b3ec606515

jpeg8_ver=8c-2ubuntu12
jpeg8_url="https://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg8-empty/libjpeg8_${jpeg8_ver}_amd64.deb"
jpeg8_sha=1403d44d2c2d3eba6a7a8aea97fab0bac2e89e144a3bf600adfdd3ecdc3d9394

jpeg_turbo8_ver=2.1.5-4ubuntu4
jpeg_turbo8_url="https://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_${jpeg_turbo8_ver}_amd64.deb"
jpeg_turbo8_sha=07672ce1f4d187e005ea0cc35d03e515ba056f3d3e7a9a25d3ef386e184da8c5

# f*ck citrix
citrix_url="https:$(curl -sL \
https://www.citrix.com/downloads/workspace-app/linux/workspace-app-for-linux-latest.html | \
grep "icaclient.*amd64.deb?__gda__" | \
sed -e 's,.*rel=",,;s," id.*,,')"
citrix_pkg="${citrix_url%\?*}"
citrix_pkg="${citrix_pkg##*/}"
citrix_sha=7ce8c3a32e1e9d698e7bca349ad582136040774a49e35f47e529430918f8b94a

citrix_usb_url="https:$(curl -sL \
https://www.citrix.com/downloads/workspace-app/linux/workspace-app-for-linux-latest.html | \
grep "ctxusb.*amd64.deb?__gda__" | \
sed -e 's,.*rel=",,;s," id.*,,')"
citrix_usb_pkg="${citrix_usb_url%\?*}"
citrix_usb_pkg="${citrix_usb_pkg##*/}"
citrix_usb_sha=b5faa627342a423cb7019bc295d9a9d7fd2785285e2ded3a7a68f1cd8dc397f7

# package_list
package_list="
discord:     ${discord_url##*/}
zoom:        ${zoom_url##*/} (${zoom_ver})
zoom-vdi:    ${zoom_vdi_url##*/}
jpeg8:       ${jpeg8_url##*/} + ${jpeg_turbo8_url##*/}
citrix:      ${citrix_pkg}
citrix-usb:  ${citrix_usb_pkg}"
