# version configuration for
# /usr/sbin/nanolx-orbit

USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:153.0) Gecko/20100101 Firefox/153.0"

discord_ver=1.0.152
discord_url="https://stable.dl2.discordapp.net/apps/linux/${discord_ver}/discord-${discord_ver}.deb"
discord_sha=60592b0117ecaf22b39d064d3f52c772f58ea83ca52cffcf742304c4bd8960a3

zoom_ver=7.1.5.4332
zoom_url="https://zoom.us/client/${zoom_ver}/zoom_amd64.deb"
zoom_sha=2c87382c0469185063fa9a3a507fea6be16882ef58c552b112297b52df3e5d18
zoom_pkg="zoom_${zoom_ver}_amd64.deb"

zoom_vdi_ver=7.0.11.27050
zoom_vdi_url="https://zoom.us/download/vdi/${zoom_vdi_ver}/zoomvdi-universal-plugin-ubuntu_${zoom_vdi_ver%.*}.deb"
zoom_vdi_sha=d400dc800ef802141a4ba38660477696eddb2304af7d6e681c6ee9f17484ac2a

run_curl=false

if [ ! -f "${pkg_base}/ctx_base.html" ]; then
    run_curl=true
else
    now=$(date +%s)
    last_mod=$(stat -c %Y "${pkg_base}/ctx_base.html")
    if [ $((now - last_mod)) -gt 1800 ]; then
        run_curl=true
    fi
fi

if [ "${run_curl}" = true ]; then
    echo -e "Gathering Citrix information (takes a few seconds).\n"

    curl -A "${USER_AGENT}" -sL "https://www.citrix.com/downloads/workspace-app/linux/workspace-app-for-linux-latest.html" > ${pkg_base}/ctx_base.html &
    pid_ctx=$!

    curl -A "${USER_AGENT}" -sL "https://www.citrix.com/downloads/workspace-app/betas-and-tech-previews/workspace-app-tp-gcc11-for-linux.html" > ${pkg_base}/ctx_beta.html &
    pid_beta=$!

    curl -A "${USER_AGENT}" -sL "https://www.citrix.com/downloads/citrix-endpoint-analysis/plug-ins/EPA-Clients-Linux.html" > ${pkg_base}/ctx_epa.html &
    pid_epa=$!

    wait ${pid_ctx} ${pid_beta} ${pid_epa}
else
    echo -e "Citrix information gathered in the past 30 Minutes, reusing.\n"
fi

citrix_base=$(< ${pkg_base}/ctx_base.html)
citrix_beta_base=$(< ${pkg_base}/ctx_beta.html)
citrix_epa_base=$(< ${pkg_base}/ctx_epa.html)

regex_ctx='rel="([^"]*icaclient[^"]*amd64\.deb\?__gda__[^"]*)"'
regex_usb='rel="([^"]*ctxusb[^"]*amd64\.deb\?__gda__[^"]*)"'
regex_epa='rel="([^"]*nsepa[^"]*\.deb\?__gda__[^"]*)"'

[[ ${citrix_base} =~ ${regex_ctx} ]] && citrix_url="https:${BASH_REMATCH[1]}"
citrix_pkg="${citrix_url%\?*}"
citrix_pkg="${citrix_pkg##*/}"
citrix_sha=5c349f97bc15802e7fa4df7b4ed29bf7d3338bc50d8f4eeefe423eafe02a6f63

[[ ${citrix_base} =~ ${regex_usb} ]] && citrix_usb_url="https:${BASH_REMATCH[1]}"
citrix_usb_pkg="${citrix_usb_url%\?*}"
citrix_usb_pkg="${citrix_usb_pkg##*/}"
citrix_usb_sha=d581ea3acdcacbdb39d3e7c33ef302d68789aaf5c7472d69356ac0ba392ea0fb

[[ ${citrix_beta_base} =~ ${regex_ctx} ]] && citrix_beta_url="https:${BASH_REMATCH[1]}"
citrix_beta_pkg="${citrix_beta_url%\?*}"
citrix_beta_pkg="${citrix_beta_pkg##*/}"
citrix_beta_sha=afb5d4186b5fda541f5992c2802474bcb3234b27db0e51a69cec3b2baee1a569

[[ ${citrix_beta_base} =~ ${regex_usb} ]] && citrix_beta_usb_url="https:${BASH_REMATCH[1]}"
citrix_beta_usb_pkg="${citrix_beta_usb_url%\?*}"
citrix_beta_usb_pkg="${citrix_beta_usb_pkg##*/}"
citrix_beta_usb_sha=7ad47272e95e81a693b76541fae982f6a6c0aa035de3416aab8e73f175494993

[[ ${citrix_epa_base} =~ ${regex_epa} ]] && citrix_epa_url="https:${BASH_REMATCH[1]}"
citrix_epa_ver=26.2.3
citrix_epa_pkg="citrix-nsepa_${citrix_epa_ver}.deb"
citrix_epa_sha=47663f97ca7b83da6c84eb9857d1bb63e56f89220f66da329c0c3b57c7f90254

package_list="

discord:           ${discord_url##*/}
zoom:              ${zoom_url##*/} (${zoom_ver})
zoom-vdi:          ${zoom_vdi_url##*/}
citrix:            ${citrix_pkg}
citrix-usb:        ${citrix_usb_pkg}
citrix-epa:        ${citrix_epa_pkg}
citrix (beta):     ${citrix_beta_pkg}
citrix-usb (beta): ${citrix_beta_usb_pkg}
"
