#!/bin/bash

version="0.0.4"
reldate="2026/05/21"

# version management in /usr/share for more flexibility
if [ -f nanolx-orbit.conf ]; then
    source nanolx-orbit.conf
else
    source /usr/share/nanolx/nanolx-orbit.conf
fi

pkg_base="/var/cache/nanolx"
mkdir -p "${pkg_base}"

curl_opts="-L --progress-bar -C -"

download_package () {
    url="${1}"
    pkg="${2}"
    sha="${3}"
    out="${pkg_base}/${4}"

    if [ -f "${out}" ]; then
        echo -e "\nPackage ${pkg} (${out##*/}) already downloaded, verifying"
        if ! echo "${sha}" "${out}" | sha256sum -c &>/dev/null; then
            echo "SHA256 checksum for ${out} is wrong"
            rm "${out}"
            noinst=true
        else
            echo "SHA256 checksum for ${out} is correct"
        fi
    else
        echo -e "\nDownloading ${pkg}: (${out})"
        curl ${curl_opts} -o "${out}" "${url}"
        if ! echo "${sha}" "${out}" | sha256sum -c &>/dev/null; then
            echo "SHA256 checksum for ${out} is wrong"
            rm "${out}"
            noinst=true
        else
            echo "SHA256 checksum for ${out} is correct"
        fi
    fi

}

install_package () {
    pkg="${pkg_base}/${1}"

    if [[ "${mode}" = "in" ]]; then
        if [[ "${noinst}" = "false" ]]; then
            gdebi -nq "${pkg}"
        else
            echo "not installing ${pkg} due to wrong SHA256 checksum"
        fi
    fi
}

handle_packages () {
    mode="${1}"
    shift

    for pkg in "${@}"; do
        noinst=false
        case ${pkg} in
            discord )
                download_package "${discord_url}" discord "${discord_sha}" "${discord_url##*/}"
                install_package "${discord_url##*/}"
            ;;
            zoom )
                download_package "${zoom_url}" zoom "${zoom_sha}" "zoom_${zoom_ver}.deb"
                install_package "zoom_${zoom_ver}.deb"
            ;;
            zoom-vdi )
                download_package "${zoom_vdi_url}" zoom-vdi "${zoom_vdi_sha}" "${zoom_vdi_url##*/}"
                install_package "${zoom_vdi_url##*/}"
            ;;
            jpeg8 )
                download_package "${jpeg8_url}" jpeg8 "${jpeg8_sha}" "${jpeg8_url##*/}"
                install_package "${jpeg8_url##*/}"

                download_package "${jpeg_turbo8_url}" libjpeg-turbo8 "${libjpeg_turbo8_sha}" "${jpeg_turbo8_url##*/}"
                install_package "${jpeg_turbo8_url##*/}"
            ;;
            citrix )
                download_package "${citrix_url}" citrix "${citrix_sha}" "${citrix_pkg}"
                install_package "${citrix_pkg}"
            ;;
            citrix-usb )
                download_package "${citrix_usb_url}" citrix-usb "${citrix_usb_sha}" "${citrix_usb_pkg}"
                install_package "${citrix_usb_pkg}"
            ;;
            openrgb-effects )
                download_package "${openrgb_effects_url}" openrgb-effects "${openrgb_effects_sha}" "${openrgb_effects_url##*/}"
                install_package "${openrgb_effects_url##*/}"
            ;;
            openrgb-hwsync )
                download_package "${openrgb_hwsync_url}" openrgb-effects "${openrgb_hwsync_sha}" "${openrgb_hwsync_url##*/}"
                install_package "${openrgb_hwsync_url##*/}"
            ;;
            openrgb-fansync )
                download_package "${openrgb_fansync_url}" openrgb-effects "${openrgb_fansync_sha}" "${openrgb_fansync_url##*/}"
                install_package "${openrgb_fansync_url##*/}"
            ;;
            * )
                echo "package ${pkg} unknown"
            ;;
        esac
    done
}

user_opt="${1}"
shift

case ${user_opt} in
    download )
        if [[ -z "${@}" ]]; then
            echo "no packages specified, exit."
            exit 0
        else
            handle_packages dl "${@}"
        fi
    ;;

    install )
        if [[ -z "${@}" ]]; then
            echo "no packages specified, exit."
            exit 0
        else
            handle_packages in "${@}"
        fi
    ;;

    list )
        echo "nanolx-orbit supports the following packages: ${package_list}"
    ;;

    clear )
        echo "removing downloaded packages from ${pkg_base}"
        rm -fv "${pkg_base}"/*
    ;;

    help | * )
        echo -e "nanolx-orbit v${version} (${reldate})
© 2026 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
    nanolx-orbit list
    nanolx-orbit download
    nanolx-orbit install
    nanolx-orbit clear
"
    ;;
esac
