# configuration for /usr/sbin/nanolx-apt

key_base=/usr/share/nanolx/trusted.d
sources_d=/usr/share/nanolx/sources.d

nanolx=https://www.nanolx.org/apt/photonic2026.asc
nanolx_store=${base}/nanolx2026.asc
nanolx_sha=8d8cbfcd9063446f19aa312cfc3c2e2a42ca9c13d6eb770157592ad39becb47f

liquorix=https://liquorix.net/liquorix-keyring.gpg
liquorix_store=${base}/liquorix.asc
liquorix_sha256=a135840be2c8578f7d341082dcc36308b2c2624cd223a598b734925efc605e3a

winehq=https://dl.winehq.org/wine-builds/winehq.key
winehq_store=${base}/winehq.asc
winehq_sha=d965d646defe94b3dfba6d5b4406900ac6c81065428bf9d9303ad7a72ee8d1b8

i2p=https://geti2p.net/_static/i2p-archive-keyring.gpg
i2p_store=${base}/i2p.asc
ip2_sha256=a14f30090dbde4be122066bdb7142704aa1450e9c90476f86ddc18e1e5f5c6ad

debmultimedia_url=https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2024.9.1_all.deb
debmultimedia_pkg=deb-multimedia-keyring_2024.9.1_all.deb
debmultimedia_sha=8dc6cbb266c701cfe58bd1d2eb9fe2245a1d6341c7110cfbfe3a5a975dcf97ca

# repo
repo_list="
debian:         https://debian.org [full suite: stable->experimental]
nanolx:         https://nanolx.org/photonic/
liquorix:       https://liquorix.net/
i2p:            https://deb.i2p.net/
winehq:         https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu
debmultimedia:  https://deb-multimedia.org/"

all_repos="debian nanolx liquorix i2p winehq deb-multimedia"
