#!/bin/bash

version="0.2.0"
reldate="2026/09/08"

if (( EUID != 0 )); then
    echo "nanolx-orbit must be run as root"
    exit 1
fi

pkg_base="/var/cache/nanolx"
mkdir -p "${pkg_base}"

source /usr/share/nanolx/nanolx-orbit.conf

curl_opts="-L --progress-bar -C -"

download_package () {
    url="${1}"
    pkg="${2}"
    sha="${3}"
    out="${pkg_base}/${4}"

    if [ -f "${out}" ]; then
        echo -e "\nPackage ${pkg} (${out##*/}) already downloaded, verifying"
        if ! echo "${sha}" "${out}" | sha256sum -c &>/dev/null; then
            echo "SHA256 checksum for ${out} is wrong"
            rm "${out}"
            noinst=true
        else
            echo "SHA256 checksum for ${out} is correct"
        fi
    else
        echo -e "\nDownloading ${pkg}: (${out})"
        curl ${curl_opts} -o "${out}" "${url}"
        if ! echo "${sha}" "${out}" | sha256sum -c &>/dev/null; then
            echo "SHA256 checksum for ${out} is wrong"
            rm "${out}"
            noinst=true
        else
            echo "SHA256 checksum for ${out} is correct"
        fi
    fi

}

install_package () {
    pkg="${pkg_base}/${1}"

    if [[ "${mode}" = "in" ]]; then
        if [[ "${noinst}" = "false" ]]; then
            gdebi -nq "${pkg}"
        else
            echo "not installing ${pkg} due to wrong SHA256 checksum"
        fi
    fi
}

install_helper () {
    local name="${1}"

    local -n url="${name//-/_}_url"
    local -n sha="${name//-/_}_sha"
    if [ -z "${2}" ]; then
        local filename="${url##*/}"
    else
        local -n filename="${name//-/_}_pkg"
    fi

    download_package "${url}" "${name}" "${sha}" "${filename}"
    install_package "${filename}"
}


handle_packages () {
    mode="${1}"
    shift

    for pkg in "${@}"; do
        noinst=false
        case ${pkg} in
            zoom-vdi )
                install_helper "${pkg}"
            ;;
            zoom | citrix | citrix-usb | citrix-epa | citrix-beta | citrix-beta-usb )
                install_helper "${pkg}" true
            ;;
            * )
                echo "package ${pkg} unknown"
            ;;
        esac
    done
}

user_opt="${1}"
shift

case ${user_opt} in
    download )
        if [[ -z "${@}" ]]; then
            echo "no packages specified, exit."
            exit 0
        else
            handle_packages dl "${@}"
        fi
    ;;

    install )
        if [[ -z "${@}" ]]; then
            echo "no packages specified, exit."
            exit 0
        else
            handle_packages in "${@}"
        fi
    ;;

    list )
        echo "nanolx-orbit supports the following packages: ${package_list}"
    ;;

    clear )
        echo "removing downloaded packages from ${pkg_base}"
        rm -fv "${pkg_base}"/*
    ;;

    version)
        echo "$(basename ${0}) ${version} (${reldate})"
    ;;

    help | * )
        echo -e "nanolx-orbit v${version} (${reldate})
© 2026 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
    nanolx-orbit list           list available packages
    nanolx-orbit download       only download desired package
    nanolx-orbit install        download and install desired package
    nanolx-orbit clear          clear temporary download directory
    nanoxl-orbit version        print version
"
    ;;
esac
