#!/bin/bash

version="1.1.0"
reldate="2016/05/25"

if [[ ${1} == "-h" || ( ${1} != "-a" && ! ${2} ) ]]; then
	if [[ ${2} ]] && shift
	echo -n ${1} | od -tx1 -An | tr -d ' '
elif [[ ${1} == "-a" ]]; then
	shift
	echo -e $(echo ${1} | sed -e 's/../\\x&/g')
else	echo "wiiconvert v${version} (${reldate})
© 2015 - 2016 Christopher Roy Bratusek <nano@jpberlin.de>

licensed under the GNU General Public License v3 (or newer)

usage:
	wiiconvert -h <wii-title-ascii-id>
	wiiconvert -a <wii-title-hex-id>

example:
	Xenoblade Chronices
	wiiconvert -h SX4P
	wiiconvert -a 53583450
"

fi
