#!/bin/bash

######
#
## Simple script to get required #
#  apt repository signing keys. ##
                                 #
                             #####
### version	2.1
### date	2022/01/02

if [[ ${EUID} != 0 ]]; then
	echo "not root - exiting"
else
	[[ $(command -v wget) == "" ]] && apt install wget
	[[ ! -d /etc/apt/keys ]] && mkdir /etc/apt/keys

	# add i386 to known architectures
	[[ $(uname -m) == *x86_64* ]] && dpkg --add-architecture i386

	# update apt index
	apt update -q -oAcquire::AllowInsecureRepositories=true

	# Debian Multimedia signing key
	# Samsung Unified Printer Driver signing key
	apt -q -oAcquire::AllowInsecureRepositories=true \
		install deb-multimedia-keyring \
			suldr-keyring

	# Remove old keys
	[[ -f /etc/apt/keys/samsung.key ]] && \
		rm -f /etc/apt/keys/samsung.key
	[[ -f /etc/apt/keys/nanolx.key ]] && \
		rm -f /etc/apt/keys/nanolx.key

	# Nanolx signing key
	[[ ! -f /etc/apt/keys/nanolx2016.key ]] && \
		wget -q https://www.nanolx.org/apt/photonic.asc \
			-O /etc/apt/keys/nanolx2016.key
	apt-key add /etc/apt/keys/nanolx2016.key

	# Liquorix signing key
	[[ ! -f /etc/apt/keys/liquorix.key ]] && \
		wget -q https://liquorix.net/linux-liquorix.pub \
			-O /etc/apt/keys/liquorix.key
	apt-key add /etc/apt/keys/liquorix.key

	# WineHQ signing key
	[[ ! -f /etc/apt/keys/winehq.key ]] && \
		wget -q https://dl.winehq.org/wine-builds/Release.key \
			-O /etc/apt/keys/winehq.key
	apt-key add /etc/apt/keys/winehq.key

	# i2p signing key
	[[ ! -f /etc/apt/keys/i2p.key ]] && \
		wget -q https://geti2p.net/_static/i2p-debian-repo.key.asc \
			-O /etc/apt/keys/i2p.key
	apt-key add /etc/apt/keys/i2p.key

	# update apt index (again)
	apt update -q -oAcquire::AllowInsecureRepositories=false
fi
